### ISSUE TITLE
Define the research question

### ISSUE THREAD

**Issue by Houdanait** [Houdanait/PoliticalTextandAttitudes#1]
The goal of this issue is to define the research question.

**Comment by matthewcwise** [comment]
Potential topics that have come to mind (still lit reviewing, suspect many of these have been explored):

1. Defining "center"--how the middle/party alignment has shifted over time
2. Is Donald trump the symptom or the cause? Does he reflect or drive the ideological shifts that are happening in American politics? What does a timeline look like? Does increasingly polarizing language coincide with rise of social media?
3. Language of dictators--comparing political speeches over time, what does an early Hitler speech sound like compared with current leaders
4. Comparisons of political views and media/movies--how much does entertainment reflect/change political discussion
5. Do sentence embedding models (eg Voyage AI) outperform other language models on political topics?
6. "neutralization of text" - can we take a text and make it more politically neutral?

**Comment by matthewcwise** [comment]
Can we predict political trends using language (super vague idea). Like the umbrella movement in China, is there something linguistic that could be done here?

**Comment by matthewcwise** [comment]
Maybe something on the more positive side of exploring polarization. Something like helping find common ground between ideological enemies?

**Comment by matthewcwise** [comment]
given the complexities involved with Arabic dialects, would there be a political research topic we could explore that involves some interesting linguistic complexity?

On a separate note, Prof. Manning mentioned unsupervised translation, which sounds like a fascinating idea to explore
https://proceedings.neurips.cc/paper_files/paper/2023/file/da31f4275972a58406b95c277ce7bc8d-Paper-Conference.pdf

**Comment by Houdanait** [comment]
With @matthewcwise we agreed on the following **research questio**n: 

Compare the language of various "extremists" politicians in different countries (and hence different languages) and see how more/less extremists they are related to one another.
